Added support for mounting file storage for oci job
oracle/accelerated-data-science pull request #139
Opened 2023-04-07 18:16 UTC by lu-ohai

### Added support for mounting file storage for oci job
- Added new API `with_storage_mount()` and `storage_mount` for `DataScienceJob`: 
- Added new dataclass `DSCFileStorage` to hold the required arguments for file system mounting
```
.with_storage_mount(
    DSCFileStorage(
        destination_directory_name="test_mount",
        mount_target="test_mount_target",
        export_path="test_export_path"
    ),
)
```
Unit test
<img width="563" alt="Screen Shot 2023-04-07 at 11 15 47 AM" src="https://user-images.githubusercontent.com/118394507/230657708-58a8a1e4-2356-4a35-99fa-f79957bc2e74.png">

2023-04-12 16:48 UTC, mayoor commented on ads/jobs/builders/infrastructure/dsc_job.py
> +        storage_mount : List[Union(DSCFileSystem, dict)
What is the format of the dict?

Could you please add code example here?

2023-04-12 19:05 UTC, qiuosier commented on ads/jobs/builders/infrastructure/__init__.py
> +from .dsc_job import DataScienceJob, DSCFileSystem, DSCFileStorage
We probably don't need the imports here.

2023-04-13 17:05 UTC, lu-ohai commented on ads/jobs/__init__.py
> +        DSCFileSystem,
Done

2023-04-13 17:05 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +class DSCFileStorage(DSCFileSystem):
Done, named it `OCIFileStorage `

2023-04-13 17:05 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +    def _update_to_dsc_model(self, **kwargs) -> dict:
Done

2023-04-13 17:08 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/__init__.py
> +from .dsc_job import DataScienceJob, DSCFileSystem, DSCFileStorage
Importing here can simplify the code, so that we can use 
```
from ads.jobs.builders.infrastructure import OCIFileStorage
```
instead of
```
from ads.jobs.builders.infrastructure.dsc_file_system import OCIFileStorage
```

2023-04-26 03:35 UTC, qiuosier requested changes

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/__init__.py
> +from .dsc_job import DataScienceJob, DSCFileSystem, DSCFileStorage
But you are not using `from ads.jobs.builders.infrastructure import OCIFileStorage` except in the test? I mean, since this is not user facing class, we don't need to import it like this. I am also ok to keep this :)

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_file_system.py
Maybe move this file to ads.common?

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/__init__.py
> +from .dsc_job import DataScienceJob, OCIFileStorage
Let's not import it here. We should make `OCIFileStorage` part of `ads.common`.

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_job.py
> +                    file_system["storageType"]
How does the `file_system` has `storageType` when user specify only `src` and `dest` for the storage mount? We should determine the `storageType` based on the format of `src`. If `src` is in the format of `ip_address:/export_path` or `mount_target_ocid:export_ocid`, then `storageType` should be `FILE_STORAGE`. In the future, if `src` is in the format of `oci://...`, we can set the `storageType` to object storage.

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +        arguments["destinationDirectoryName"] = arguments.pop("dsc")
we are using `dest`, not `dsc`, right?

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_job.py
> +            storage_mount_list.append(DSCFileSystemManager.initialize(item))
we should keep only `src` and `dest` in the yaml/spec and initialize the `OCIFileStorage` when creating the job.

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +        elif "mount_target_id" in arguments or "export_id" in arguments:
We don't want the users to specify mount_target_id and export_id separately. We should support the `src` with the format of `mount_target_id:export_id`

2023-04-26 03:35 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +                ipaddress.IPv4Network(arguments["src"].split(":")[0])
How does the IP address get converted to mount_target_id? This line does not seem to do anything for the `OCIFileStorage`?

2023-04-26 16:48 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +        arguments["destinationDirectoryName"] = arguments.pop("dsc")
Will update

2023-04-26 16:49 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/dsc_job.py
> +            storage_mount_list.append(DSCFileSystemManager.initialize(item))
Will update

2023-04-26 16:49 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +        elif "mount_target_id" in arguments or "export_id" in arguments:
I see, will update

2023-04-26 16:52 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/dsc_file_system.py
> +                ipaddress.IPv4Network(arguments["src"].split(":")[0])
It doesn't, just want to use this API to validate if it's ip address, the `mount_target_id` is converted when called `update_to_dsc_model()`. But since the `src` could be `<mount_target_id>:<export_id>` this can be modified. Will update.

2023-04-26 22:18 UTC, lu-ohai commented on ads/jobs/builders/infrastructure/__init__.py
> +from .dsc_job import DataScienceJob, DSCFileSystem, DSCFileStorage
Done

2023-04-28 22:53 UTC, qiuosier submitted a review, later dismissed

2023-04-28 22:53 UTC, qiuosier commented on ads/jobs/builders/infrastructure/dsc_job.py
> +	                "dest" : "<destination_directory_name>"
Align "src" and "dest"
```suggestion
	            "dest" : "<destination_directory_name>"
```

2023-04-28 22:54 UTC, qiuosier approved these changes

2023-04-28 22:56 UTC, z7ye approved these changes

2023-04-29 00:06 UTC, merged