ODSC-46642/pass model by reference
oracle/accelerated-data-science pull request #342
Opened 2023-09-21 15:49 UTC by mingkang111

# Description
https://jira.oci.oraclecorp.com/browse/ODSC-46642
Improve the [LargeArtifactUploader](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/artifact_uploader.py#L106) class to understand OCI paths to upload model artifacts to the model catalog by reference.

# Changed
* Case1: user want to copy the model artifact in [ARTIFACT_PATH](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L131) to [bucket_uri](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L547), and then upload to MC. (this is the current case we are supporting).
* Case 2: user wants to upload model artifacts in [bucket_uri](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L547) to MC. (this is the new case we want to support)

Allow the [ARTIFACT_PATH](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L131)  to be oci:// path, and only allow for model zip file. e.g: `oci://xxx@tenency/my_model.zip` . Then if user is targeting on case2,  user can pass `ARTIFACT_PATH="oci://xxx@tenency/my_model.zip"`, we can set [bucket_uri](https://github.com/oracle/accelerated-data-science/blob/main/ads/model/datascience_model.py#L547)  for them internally.

# User experience
* Uploading any size model (include the LLM models) already exists in Object Storage
```
import ads
from ads.model import DataScienceModel

ads.set_auth("resource_principal")

MODEL_DISPLAY_NAME = "my_large_model"
OCI_BUCKET = "oci://bucket@namespace/prefix/my_large_model.zip"

model = (DataScienceModel()
         .with_display_name(MODEL_DISPLAY_NAME)
         .with_artifact(OCI_BUCKET)
         .create(
            overwrite_existing_artifact=True, # Overwrite target bucket artifact if exists.
            remove_existing_artifact=True # Whether artifacts uploaded to the object storage bucket need to be removed or not.
         )
        ) 
```

* Uploading the large models not exists in Object Storage, but in local
```
import ads
from ads.model import DataScienceModel

ads.set_auth("resource_principal")

MODEL_DISPLAY_NAME = "my_large_model"
ARTFICAT_FILE_NAME = "./my_large_model.zip"  
OCI_BUCKET = "oci://bucket@namespace/prefix/my_large_model.zip"

model = (DataScienceModel()
         .with_display_name(MODEL_DISPLAY_NAME)
         .with_artifact(ARTFICAT_FILE_NAME)
         .create(
            bucket_uri=OCI_BUCKET, # model artifact already in this path
            overwrite_existing_artifact=True, # Overwrite target bucket artifact if exists.
            remove_existing_artifact=True # Whether artifacts uploaded to the object storage bucket need to be removed or not.
         )
        ) 
```
* Uploading the small model in local
```
import ads
from ads.model import DataScienceModel

ads.set_auth("resource_principal")

MODEL_DISPLAY_NAME = "my_large_model"
ARTFICAT_FILE_NAME = "./my_large_model.zip"  

model = (DataScienceModel()
         .with_display_name(MODEL_DISPLAY_NAME)
         .with_artifact(ARTFICAT_FILE_NAME)
         .create( )
        ) 
```

# Test
TBD

2023-09-23 18:41 UTC, mrDzurb commented
If user provides the path to zip in OS bucket, let's auto extract the 
```bucket_uri=OCI_BUCKET, # model artifact already in this path``` 
However if user provides different ```bucket_uri```, then let's show a warning and say that this argument will be ignored for the case when ```.with_artifact(ARTFICAT_FILE_NAME)``` is a path to zip archive. Also let's always use the large artifact uploader if user provides the path to zip archive in Object Storage.

2023-09-23 18:41 UTC, mrDzurb commented on ads/model/artifact_uploader.py
> +                    f"The `artifact_path={artifact_path}` is invalid. Please check APIs doc to see the possible values for it."
Let's make the message more informative for user. Something similar that you've put o the method description.

2023-09-26 17:24 UTC, mingkang111 commented on ads/model/artifact_uploader.py
> +                    f"The `artifact_path={artifact_path}` is invalid. Please check APIs doc to see the possible values for it."
Fixed!

2023-09-26 17:28 UTC, mingkang111 commented
> If user provides the path to zip in OS bucket, let's auto extract the `bucket_uri=OCI_BUCKET, # model artifact already in this path` However if user provides different `bucket_uri`, then let's show a warning and say that this argument will be ignored for the case when `.with_artifact(ARTFICAT_FILE_NAME)` is a path to zip archive. Also let's always use the large artifact uploader if user provides the path to zip archive in Object Storage.

Yes. As we discussed, the warning messages have been added in `ads/model/datascience_model.py`.  When the user passes a remote path for the model artifact, we will automatically assign value to `bucket_uri`, so the `LargeArtifactUploader` will always be used. Thanks for the feedback!

2023-09-26 20:41 UTC, mrDzurb approved these changes

2023-09-27 00:31 UTC, z7ye requested changes

2023-09-27 00:31 UTC, z7ye commented on ads/model/datascience_model.py
> +            if bucket_uri and bucket_uri != self.artifac:
self.artifac -> self.artifact

2023-09-27 00:44 UTC, mingkang111 commented on ads/model/datascience_model.py
> +            if bucket_uri and bucket_uri != self.artifac:
Thanks @z7ye ! Fixed!

2023-09-27 00:47 UTC, z7ye approved these changes

2023-09-27 16:34 UTC, mrDzurb approved these changes

2023-09-27 17:02 UTC, merged