Updated forecast operator schema for preprocessing
oracle/accelerated-data-science pull request #741
Opened 2024-03-22 08:10 UTC by prasankh

* Revised schema for preprocessing
```
preprocessing: 
 enabled: true
 steps:
   missing_value_imputation: true
   outlier_treatment: false
```
* updated test cases to cover multiple such scenarios

2024-03-24 11:04 UTC, ahosler requested changes
A couple of small follow up qs

2024-03-24 11:04 UTC, ahosler commented on ads/opctl/operator/lowcode/forecast/schema.yaml
> +      schema:
Is the structure
preprocessing : {enabled, steps: {missing_val, outlier_d}}
or
 preprocessing : {enabled, missing_val, outlier_d}

Aren't the schema.yaml and operator_config disagreeing?

2024-03-24 11:04 UTC, ahosler commented on tests/operators/forecast/test_errors.py
>          # 4 columns in historical data, but only 1 cat col specified
Can we add a test that reads the output file (forecast.csv) and asserts that the "input_value" column matches the historical data when "outlier_detection": False.
Then show that they are not equal when "outlier_detection": True

2024-03-26 03:50 UTC, prasankh commented on ads/opctl/operator/lowcode/forecast/schema.yaml
> +      schema:
The first one, updated schema.yaml

2024-03-26 03:50 UTC, prasankh commented on tests/operators/forecast/test_errors.py
>          # 4 columns in historical data, but only 1 cat col specified
Done

2024-04-11 12:52 UTC, ahosler approved these changes

2024-04-12 08:35 UTC, closed without merging