Unittest for aqua.evaluation
oracle/accelerated-data-science pull request #761
Opened 2024-04-08 21:30 UTC by mingkang111

# Description
This PR adds more test cases for aqua.evaluation. Increased the coverage to 
![Screenshot 2024-04-08 at 17 17 18](https://github.com/oracle/accelerated-data-science/assets/49049296/ccfa1786-7a8a-4c53-b0d3-0d1c73cbef2b)

# TODO
Add test case for CREATE EVAL from @lu-ohai 

# Test 
![Screenshot 2024-04-08 at 17 30 37](https://github.com/oracle/accelerated-data-science/assets/49049296/95720e2b-6d3f-4c2b-84a0-0913ea6b91d8)

2024-04-08 21:53 UTC, VipulMascarenhas approved these changes

2024-04-08 22:16 UTC, mingkang111 commented on ads/aqua/evaluation.py
> +        job_run_id = (
This is the fix for the existing potential bug in production: when `model.provenance_metadata` is None, the function will break.

2024-04-08 22:19 UTC, mingkang111 commented on ads/aqua/evaluation.py
> +        except Exception:
`model.custom_metadata_list` can be None for DataScienceModel, which will give 500 `AttributeError` from ads. We need to make it as `AquaMissingKeyError` as well.

2024-04-08 22:20 UTC, mingkang111 commented on ads/aqua/evaluation.py
> -    def _get_jobrun(
The function has not been used. So it is safe to remove it.

2024-04-08 22:26 UTC, VipulMascarenhas requested changes
can we revert the changes in evaluation.py and add the changes separately later on? This PR will change the current behavior in production even if the intention is to fix bugs. All these changes can go as a part of the next set of improvements/bug fixes later on.

2024-04-09 14:20 UTC, mingkang111 commented
> can we revert the changes in evaluation.py and add the changes separately later on? This PR will change the current behavior in production even if the intention is to fix bugs. All these changes can go as a part of the next set of improvements/bug fixes later on.

These changes as I commented, are worthwhile to be fixed. They didn't touch the main logic. I believe it is the reason for writing test: to find the bug and fix them. I will keep this PR open to be merged later. 
I also prepared another PR: https://github.com/oracle/accelerated-data-science/pull/763 which is the version that adding test without the change in `evaluation.py`. In case @mayoor prefer to merge those first.

2024-04-19 17:50 UTC, VipulMascarenhas approved these changes
thanks for this PR, changes look good.

2024-04-19 18:04 UTC, merged

2024-04-20 03:41 UTC, mrDzurb commented on ads/aqua/evaluation.py
> +        model_provenance = self.ds_client.get_model_provenance(eval_id).data
Can we guarantee that the ```.data``` will be available always?  What will happen in negative scenario?

2024-04-20 03:41 UTC, mrDzurb commented on ads/aqua/evaluation.py
> +            model.provenance_metadata.training_id if model.provenance_metadata else None
Can't the ```model.provenance_metadata``` be None by itself?

2024-04-22 14:02 UTC, mingkang111 commented on ads/aqua/evaluation.py
> +            model.provenance_metadata.training_id if model.provenance_metadata else None
Hi @mrDzurb , the model here is ads `DataScienceModel`, which is guaranteed to have `provenance_metadata` property.

2024-04-22 14:14 UTC, mingkang111 commented on ads/aqua/evaluation.py
> +        model_provenance = self.ds_client.get_model_provenance(eval_id).data
Based on how oci python sdk implement it, as long as `self.ds_client.get_model_provenance(eval_id)` gives response, it will have `data` property. See https://github.com/oracle/oci-python-sdk/blob/master/src/oci/base_client.py#L747 and https://github.com/oracle/oci-python-sdk/blob/master/src/oci/response.py#L8

We have verify this before as well: https://github.com/oracle/accelerated-data-science/blob/main/ads/model/service/oci_datascience_model.py#L240