Feature/multi model artifact handler
oracle/accelerated-data-science pull request #869
Opened 2024-05-27 19:49 UTC by YashPandit4u

Adding a new class to easily hadle multi-model artifact creation in ADS.

2024-05-29 16:40 UTC, darenr requested changes

2024-05-29 16:40 UTC, darenr commented on ads/model/model_description.py
> +            print("Getting model details from backend")
all the print statements should be moved to logger.info/debug please

2024-05-29 16:40 UTC, darenr commented on ads/model/model_description.py
> +            except FileNotFoundError:
we should just let the exception propagate up - this is too much like Java :)

2024-05-29 16:40 UTC, darenr commented on ads/model/model_description.py
> +                    print(f"File not found in bucket: {fileName}")
logger.error

2024-05-29 16:40 UTC, darenr commented on ads/model/model_description.py
> +                    )
this code doesn't look like it was run through the pre-commit ruff/black formatter?

2024-05-29 16:40 UTC, darenr commented on ads/model/model_description.py
> +            return
is this an error condition?

2024-05-29 16:40 UTC, darenr commented on ads/model/model_description.py
> +    region = ''
should't this be in the __init__ ctor?

2024-06-01 14:23 UTC, YashPandit4u commented on ads/model/model_description.py
> +    region = ''
Yes thanks, done.

2024-06-01 14:33 UTC, YashPandit4u commented on ads/model/model_description.py
> +                    print(f"File not found in bucket: {fileName}")
Done

2024-06-01 14:54 UTC, YashPandit4u commented on ads/model/model_description.py
> +            except FileNotFoundError:
Yes, thanks for the comment. Now have raised errors everywhere needed.

Note for this code piece: Now I have changed the code a bit, instead of populating the file with API response and then reading the file contents into a local variable, I have skipped the file part.

2024-06-01 14:54 UTC, YashPandit4u commented on ads/model/model_description.py
> +            print("Getting model details from backend")
Done

2024-06-01 14:55 UTC, YashPandit4u commented on ads/model/model_description.py
> +            return
Yes, it is, now I have raised a "ValueError" in this case.

2024-06-01 15:22 UTC, YashPandit4u commented on ads/model/model_description.py
> +                    )
Manually ran black.

2024-06-03 22:11 UTC, VipulMascarenhas commented on ads/model/model_description.py
> +logger = logging.getLogger("ads.model_description")
can we reuse the logger from `ads.common`?

2024-06-04 01:01 UTC, VipulMascarenhas reviewed
left a few comments, I think we should be reusing most of the implementation from DataScienceModel class instead of recreating it in here. A high level design would look like: 

```
class DataScienceModelCollection(DataScienceModel):

    def __init__():
        super().__init__(**kwargs)
        # no need to add model self.modeldescriptionjson since this attribute is already present in DataScienceModel
    
    def add():
        ...
        
    def remove():
        ...
        
    def show():
        ...     
```

The usage would look like:
```
    >>> model = (DataScienceModelCollection()
    ...    .with_compartment_id()
    ...    .with_project_id()
    ...    .with_display_name()
    ...    .with_description()
    ...    .with_freeform_tags()
    ...    .with_artifact("model1_path", "model2_path")

    >>> model.add(...)
    >>> model.remove(...)
    >>> model.create(model_by_reference=True)
```
any thoughts on this?

2024-06-04 05:46 UTC, Abh1navKumar requested changes

2024-06-04 05:46 UTC, Abh1navKumar commented on ads/model/model_description.py
> +            "Created by MMS SDK on "
Yes it should be ADS SDK now.

2024-06-04 05:46 UTC, Abh1navKumar commented on ads/model/model_description.py
> +    def auth(self):
do we need to have this Auth() func ? 
Customer usually set the Auth using ads.setAuth() once which is used in all the ADS SDK interactions.

2024-06-04 05:46 UTC, Abh1navKumar commented on ads/model/model_description.py
> +        logger.info(json.dumps(self.modelDescriptionJson, indent=4))
Agree. It should return the modelDescriptionJson to user. They can print it themselves if needed or reuse it.

2024-06-04 05:46 UTC, Abh1navKumar commented on ads/model/model_description.py
> +    def save(self, project_ocid, compartment_ocid, display_name=None):
Please define types for type checking.

2024-06-04 13:20 UTC, YashPandit4u commented on ads/model/model_description.py
> +            "Created by MMS SDK on "
Done, changed to ADS

2024-06-05 03:34 UTC, mrDzurb reviewed
I may have misunderstood what we're trying to achieve in this PR, but wouldn't a user experience like the following be more streamlined?

```python
model_description = ModelDescription().add("oci://bucket_name@namespace/prefix1", "oci://bucket_name@namespace/person_prefix2")
```

Here, `ModelDescription` acts as a builder for the JSON configuration needed.
It still can contain all the introduced methods in this PR: add, remove, build, print...

I would prefer  instead of ```.build to use``` ```.to_json(uri="path/to/the/json")``` where if user don't provide uri then JSON should be returned as a result of the function. Also adding ```.to_dict()``` might be useful as well.
In this case we don't need ```.show()``` method.

We could then enhance the `DatascienceModel` class with:

```python
DatascienceModel().with_model_description(model_description).create()
```

This approach leverages the existing `DatascienceModel` class, which already supports CRUD operations for models, so we wouldn't need to replicate these in the `ModelDescription` class. The purpose of `ModelDescription` would be to simplify the preparation of the correct JSON configuration for users. 

Perhaps we could consider a clearer name for clarity, as "ModelDescription" might be somewhat confusing. How about using "ModelArtifactConfigBuilder" to more accurately reflect its purpose as a tool for constructing model artifact configurations?

Then user experience would be 

```python

model_artifact_config = ModelArtifactConfigBuilder().add().add()

DatascienceModel().with_model_artifact(model_artifact_config).create()
```

cc: @mayoor @VipulMascarenhas

2024-06-05 09:58 UTC, YashPandit4u commented on ads/model/model_description.py
> +        def findModelIdx():
Done

2024-06-05 10:00 UTC, YashPandit4u commented on ads/model/model_description.py
> +        logger.info(json.dumps(self.modelDescriptionJson, indent=4))
Added return too

2024-06-05 10:04 UTC, YashPandit4u commented on ads/model/model_description.py
> +    def add(self, namespace, bucket, prefix=None, files=None):
Added type hints.

2024-06-05 10:09 UTC, YashPandit4u commented on ads/model/model_description.py
> +            if (display_name == None)
The suggested statement will trigger even when we have blank string.

2024-06-05 10:10 UTC, YashPandit4u commented on ads/model/model_description.py
> +        model_details = oci.data_science.models.CreateModelDetails(
Did this now by extending this class from DataScienceModel

2024-06-05 10:11 UTC, YashPandit4u commented on ads/model/model_description.py
> +        customMetadataList = [Metadata(key="modelDescription", value="true")]
As we are now using create from the parent class this code piece is removed.

2024-06-05 10:12 UTC, YashPandit4u commented on ads/model/model_description.py
> +    def auth(self):
This internal _auth() is used in __init__() ans is used to authenticate object storage client based on details given by the ads auth.

2024-06-05 10:12 UTC, YashPandit4u commented on ads/model/model_description.py
> +    def save(self, project_ocid, compartment_ocid, display_name=None):
Thanks, did this for all methods.

2024-06-05 10:21 UTC, YashPandit4u commented
Hi  @VipulMascarenhas ,

I have now extended from the class already present in ads and the usage of the utility looks like this now:

`import sys
import ads.common
from ads.model.model_collection import DataScienceModelCollection
import ads
import json

# Auth
ads.set_auth(auth="security_token")


mdes = DataScienceModelCollection() \
    .with_ref_model_id(model_ocid="ocid1.datasciencemodel.oc1.iad.amaaaaaav66vvnialtuoq5y4ltdz26bxhlow4uh5w544ullowe3jl4vwuayq") \
    .with_display_name("New Design 8") \
    .with_compartment_id("ocid1.tenancy.oc1..aaaaaaaahzy3x4boh7ipxyft2rowu2xeglvanlfewudbnueugsieyuojkldq") \
    .with_project_id("ocid1.datascienceproject.oc1.iad.amaaaaaav66vvniaqsyu2nufljutkn4rzth2nz4q3zqslirct7eayl5ojpma")

mdes.add(namespace="ociodscdev", bucket="unzip-multi-model", prefix="model-linear-1")
mdes.remove(namespace="ociodscdev", bucket="unzip-multi-model", prefix="model-linear-1")

mdes.create()

sys.exit(0)

`

Please take a look when free and give your comments.

Thanks and Regards
Yash Pandit

2024-06-05 11:15 UTC, Abh1navKumar commented on ads/model/model_collection.py
> +    def show(self):
we need to add return type as str also.

2024-06-05 11:23 UTC, Abh1navKumar commented on ads/model/model_collection.py
> +        def check_if_file_exists(fileName):
Wrong indentation.

2024-06-05 16:28 UTC, mrDzurb commented on ads/model/model_collection.py
> +    def _auth(self):
I don't think that we need this method here. The all operations with the service take place within the ```OCIDataScienceModel``` which is already has such method. Please take a look how the ```DatascienceModel.create``` method works.

```python
# Create model in the model catalog
logger.info("Saving model to the Model Catalog.")
self.dsc_model = self._to_oci_dsc_model(**kwargs).create()
```

However if we still need to create a client, then it would be better to use ```OCIClientFactory```. 
Something like:

```
def create_os_client(self):
        return oci_client.OCIClientFactory(**self.auth).object_storage
```

2024-06-05 16:28 UTC, mrDzurb commented on ads/model/model_collection.py
> +logger = logging.getLogger("ads.model_description")
Wouldn't this be better - ```logger = logging.getLogger(__name__)```?

2024-06-05 16:33 UTC, mrDzurb commented on ads/model/model_collection.py
> +        def check_if_file_exists(fileName):
Please double check if the existing utils methods are already implemented such functionality.

2024-06-11 01:07 UTC, VipulMascarenhas reviewed
@YashPandit4u suggested a few changes, just needs to be re-organized to make it consistent with ads usage.

2024-06-11 01:07 UTC, VipulMascarenhas commented on ads/model/model_collection.py
> +    def build(self) -> str:
we had reservations around calling this `build` since conventionally build function should return self/object. User can just do `json.dump(model.model_file_description)` but if we really need this functionality, it would be good to have different function name.

2024-06-11 01:07 UTC, VipulMascarenhas commented on ads/model/model_collection.py
> +    def show(self) -> str:
this is covered by `model.model_file_description` property.

2024-06-11 12:22 UTC, YashPandit4u commented on ads/model/model_collection.py
> +    def show(self) -> str:
Yes removing this.

2024-06-11 12:22 UTC, YashPandit4u commented on ads/model/model_collection.py
> +    def build(self) -> str:
Okay

2024-06-11 12:22 UTC, YashPandit4u commented on ads/model/model_collection.py
> +    def create(self):
Yes removed this.

2024-06-11 12:24 UTC, YashPandit4u commented on ads/model/model_collection.py
> +            for idx, model in enumerate(self.model_file_description["models"]):
Thanks, added this condition.

2024-06-11 12:24 UTC, YashPandit4u commented on ads/model/model_collection.py
> +    def remove(self, namespace: str, bucket: str, prefix: Optional[str] = None):
Yes done.

2024-06-11 12:26 UTC, YashPandit4u commented on ads/model/model_collection.py
> +    def add(
The user won't have uri handy, hence we have parameters like namespace, and bucket to make it easy. 
Will it be possible to keep these parameters? The function signature would look like:

`def add_artifact(
        self,
        namespace: str,
        bucket: str,
        prefix: Optional[str] = None,
        files: Optional[List[str]] = None,
    )`

2024-06-11 12:27 UTC, YashPandit4u commented on ads/model/model_collection.py
> +class DataScienceModelCollection(DataScienceModel):
Yes, now I have added the add_artifact and remove_artifact methods in the DataScienceModel class itself.

2024-06-11 12:40 UTC, YashPandit4u commented on ads/model/model_collection.py
> +        self.set_spec(self.CONST_MODEL_FILE_DESCRIPTION, tmp_model_file_description)
Thanks for this suggestion.
Will it be okay if we do this in the next PR due to customer deadlines?

2024-06-11 23:57 UTC, VipulMascarenhas commented on ads/model/model_collection.py
> +        self.set_spec(self.CONST_MODEL_FILE_DESCRIPTION, tmp_model_file_description)
sure, let's mark a todo somewhere to make sure of this.

2024-06-12 00:01 UTC, VipulMascarenhas commented on ads/model/model_collection.py
> +    def add(
isn't the uri same as `f"oci://{bucketName}@{namespace}/{prefix}"`, all of which are added as input to this function. My concern is that this input makes it incosistent with all other `DataScienceModel` or `GenericModel` operations in ads and we wouldn't be able to change it later on. 
@mrDzurb what do you think?

2024-06-12 00:42 UTC, VipulMascarenhas commented
@YashPandit4u thanks for making all the changes here, looks good overall. One concern I have is around the path inputs, it would be good to have the oci path like I mentioned in the comments above as user can construct the path easily with the params (bucket, namespace and prefix).  Also, could you please add a couple unit tests in `test_datascience_model.py` for this change? 

cc: @mrDzurb

2024-06-12 00:56 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        namespace: str,
For consistency it would be better to accept OCIFS "oci://" path.

2024-06-12 00:56 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        Parameters:
NIT: for the pydocs we have a bit different format

```
Parameters
------------
namespace (str): The namespace of the object storage.

Returns
--------
None

Raises
------
 ValueError: If no files are found to add to the model description.

```

2024-06-12 00:56 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        authData = default_signer()
Technically the auth object is already constructed and accessible by 
```
self.dsc_model.auth
```

2024-06-13 13:01 UTC, YashPandit4u commented on ads/model/datascience_model.py
> +        authData = default_signer()
Thanks, using this now.

2024-06-13 14:10 UTC, YashPandit4u commented on ads/model/datascience_model.py
> +        Parameters:
Changed docs to this format.

2024-06-13 14:11 UTC, YashPandit4u commented on ads/model/datascience_model.py
> +        namespace: str,
Have changed both functions add_artifact and remove_artifact with this uri type input.

2024-06-13 17:06 UTC, VipulMascarenhas submitted a review, later dismissed
@YashPandit4u thanks for the update. There are a few improvements to make for the next update: 
- check_if_file_exists and list_obj_versions_unpaginated should reuse existing methods.
- _extract_oci_uri_components wasn't required, as mentioned in previous comments we could just use `ObjectStorageDetails.from_path(uri)` to get bucket name, namespace and prefix. If we want to add validation ObjectStorageDetails has a few static methods like `is_valid_uri` to do this.

2024-06-13 17:38 UTC, YashPandit4u commented
Hi @VipulMascarenhas , thanks for telling the improvement items. 
* I have now removed the "_extract_oci_uri_components" method and used the already present ObjectStorageDetails.from_path(uri) to get the namespace, prefix, and filepath. Thanks for the suggestion.

2024-06-13 17:51 UTC, VipulMascarenhas submitted a review, later dismissed
lgtm 👍

2024-06-14 19:10 UTC, YashPandit4u commented
Hi @VipulMascarenhas ,
Based on the management decision, I have reverted the method signatures to the ones suggested by the customer.

2024-06-15 10:38 UTC, YashPandit4u commented
Hi @VipulMascarenhas ,
 
 I have now added options for both uri and (namespace, bucket, prefix) in add_artifact, remove_artifact.

2024-06-17 17:39 UTC, mrDzurb approved these changes

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +    def add_artifact(
NIT: Could you please add an examples section for the add and delete artifacts feature?

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        if (not namespace) or (not bucket):
NIT: ```if not (namespace and bucket):```

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +            raise ValueError("Both 'namespace' and 'bucket' must be provided.")
NIT: Wouldn't it be better to say something like - ```Artifacts cannot be added. Both 'namespace' and 'bucket' parameters must be provided.```. otherwise it would be hard for user to understand where they need to provide the namespace and bucket.

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        if uri and (namespace or bucket):
Maybe we can do something like this?

```
if uri and (namespace or bucket):
    raise ValueError("Artifacts cannot be added. Please provide either a 'uri' alone, or 'namespace' and 'bucket' together, but not 'uri' with 'namespace' or 'bucket'.")

elif not (uri or (namespace and bucket)):
    raise ValueError("Artifacts cannot be added. You must provide either a 'uri' or both 'namespace' and 'bucket'.")

```

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        def check_if_file_exists(fileName):
NIT: I would not recommend to create nested functions, it would be hard to write unit tests for such methods. I would rather recommend to move such methods into utils or outside the class.

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +            error_message = (
NIT: 

```
error_message = (
        f"No files found to add in the bucket '{bucket}' within the namespace '{namespace}' "
        f"and prefix '{prefix}'. Expected file names: {files}"
    )
```

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +    def remove_artifact(
Please add the examples section.

2024-06-17 17:39 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        if uri and (namespace or bucket):
See the comments for the add_artifact method.

2024-06-17 18:04 UTC, VipulMascarenhas approved these changes

2024-06-18 16:15 UTC, merged