Adding supported architectures for containers configuration
oracle/accelerated-data-science pull request #900
Opened 2024-07-08 04:33 UTC by harsh97

2024-07-08 16:23 UTC, VipulMascarenhas requested changes
few changes requested:
- can you change the target branch to feature/aquav1.0.3 instead of main?
- can we rename `arch` to `platform` instead?
- some tests are failing, might be good to fix them before we merge these changes.

2024-07-10 01:01 UTC, VipulMascarenhas reviewed
left a few comments.

2024-07-10 19:05 UTC, VipulMascarenhas commented on ads/aqua/common/utils.py
> +    fs = ocifs.OCIFileSystem(**signer)
we can reuse `list_objects` from `object_storage_details.py` instead.

2024-07-11 18:45 UTC, harsh97 commented on .pre-commit-config.yaml
> +            exclude: .github/workflows/reusable-actions/set-dummy-conf.yml|./tests/operators/common/test_load_data.py
line =       self.data_spec.vault_secret_id = 'mock_secret_id' was being flagged as secret violation

2024-07-11 18:50 UTC, harsh97 commented on ads/aqua/model/model.py
> +            **self.to_aqua_model(ds_model, self.region),
have created a new method instead

2024-07-11 18:51 UTC, harsh97 commented on ads/aqua/model/model.py
> +            freeform_tags.get(Tags.GPU_MODEL, "").upper == GPU_SUPPORTED_STATUS
as discussed platform will now be derrived from continer config and model_format

2024-07-11 18:51 UTC, harsh97 commented on ads/aqua/modeldeployment/deployment.py
> +            # Todo: Revisit this logic when we have multi arch support
discussed offline and removed this change

2024-07-11 19:15 UTC, harsh97 commented on ads/aqua/common/utils.py
> +    fs = ocifs.OCIFileSystem(**signer)
addressed. Thanks!

2024-07-11 19:16 UTC, harsh97 commented on ads/aqua/config/deployment_config_defaults.json
> +  "CPU": {
updated

2024-07-12 00:27 UTC, VipulMascarenhas approved these changes
changes look good, add minor comments. I'm curious to see if the API latency increases for some of the calls we're making to fetch info from config files.

2024-07-12 00:27 UTC, VipulMascarenhas commented on ads/aqua/common/utils.py
> +    signer = default_signer()
nit: remove redundant code

2024-07-12 00:27 UTC, VipulMascarenhas commented on ads/aqua/model/model.py
> +class ModelValidationResult:
nit: this can go inside `ads.aqua.model.entities`

2024-07-12 00:27 UTC, VipulMascarenhas commented on ads/aqua/model/model.py
> +        inference_containers = AquaContainerConfig.from_container_index_json().inference
we should check if this adds any increase in latency for get() API as any file read operation will introduce significant delay.

2024-07-12 00:27 UTC, VipulMascarenhas commented on ads/aqua/model/model.py
> +    def get_model_files(os_path: str, model_format: ModelFormat) -> [str]:
nit: add docstrings

2024-07-12 00:27 UTC, VipulMascarenhas commented on ads/aqua/model/model.py
> +    def validate_model_config(
nit: add docstrings

2024-07-12 04:51 UTC, harsh97 commented on ads/aqua/model/model.py
> +        inference_containers = AquaContainerConfig.from_container_index_json().inference
I have added a cache on the file read in utils function!!

2024-07-12 04:54 UTC, harsh97 commented on ads/aqua/model/model.py
> +    def validate_model_config(
done

2024-07-12 04:54 UTC, harsh97 commented on ads/aqua/model/model.py
> +    def get_model_files(os_path: str, model_format: ModelFormat) -> [str]:
done

2024-07-12 04:54 UTC, harsh97 commented on ads/aqua/model/model.py
> +class ModelValidationResult:
done

2024-07-12 04:54 UTC, harsh97 commented on ads/aqua/common/utils.py
> +    signer = default_signer()
done

2024-07-12 04:56 UTC, merged