Add sf merlion for time-based ad
oracle/accelerated-data-science pull request #956
Opened 2024-09-29 18:05 UTC by codeloop

Add sf merlion for time-based ad

2024-10-08 14:24 UTC, ahosler requested changes
In testing, I see that the anomaly score is no longer normalized from 0-1. Does Merlion have a different interpretation for the meaning of this score (CSV uploaded)? 
I believe we should stick with the [0,1] convention unless we have good reason to change.

Also Merlion seemed over-reactive on a few of the tests I've run. Are there any default settings we should be tweaking?

[outliers.csv](https://github.com/user-attachments/files/17294813/outliers.csv)

2024-10-08 14:24 UTC, ahosler commented on pyproject.toml
> +  "salesforce-merlion[all]==2.0.4"
What features does the "all" get us?

2024-10-08 14:24 UTC, ahosler commented on ads/opctl/operator/lowcode/anomaly/schema.yaml
> +        - merlion_ad
can we change this to "merlion"?

2024-10-08 14:24 UTC, ahosler commented on ads/opctl/operator/lowcode/anomaly/model/randomcutforest.py
> +        anomaly_threshold = model_kwargs.get("anomaly_threshold", 95)
great catch

2024-10-17 12:05 UTC, codeloop commented on pyproject.toml
> +  "salesforce-merlion[all]==2.0.4"
`[all]` comprises of AD, forecast needed for AD, DL support we have some deep learning based AD algos, + few things on distributed processing & others.

2024-10-17 16:44 UTC, codeloop commented
> 1. In testing, I see that the anomaly score is no longer normalized from 0-1. Does Merlion have a different interpretation for the meaning of this score ? (CSV uploaded below)
>    I believe we should stick with the [0,1] convention unless we have good reason to change.
> 2. Also Merlion seemed over-reactive on a few of the tests I've run. Are there any default settings we should be tweaking?
> 3. Could Merlion be made to work for non-timeseries AD? Or is it primarily time-based?
> 
> [outliers.csv](https://github.com/user-attachments/files/17294813/outliers.csv)



> 1. In testing, I see that the anomaly score is no longer normalized from 0-1. Does Merlion have a different interpretation for the meaning of this score ? (CSV uploaded below)
>    I believe we should stick with the [0,1] convention unless we have good reason to change.
> 2. Also Merlion seemed over-reactive on a few of the tests I've run. Are there any default settings we should be tweaking?
> 3. Could Merlion be made to work for non-timeseries AD? Or is it primarily time-based?
> 
> [outliers.csv](https://github.com/user-attachments/files/17294813/outliers.csv)

1. Added score normalization.
2. We can use an alarm threshold param to control the sensitivity of the models.
3. Currently it only supports time-series data.

2024-10-21 11:53 UTC, prasankh approved these changes

2024-10-22 13:14 UTC, ahosler approved these changes

2024-10-22 13:14 UTC, merged