Feature/ms backup retention
oracle/accelerated-data-science pull request #962
Opened 2024-10-09 05:00 UTC by iamishaan

Added changes for Model backup and retention, updated test cases

2024-10-09 18:35 UTC, lu-ohai commented
@iamishaan Could you add some user experience example here and also update the user guide? DataScience Model related user guide should be placed under [here](https://accelerated-data-science.readthedocs.io/en/latest/user_guide/model_registration/introduction.html).

2024-10-14 16:40 UTC, lu-ohai requested changes
Added some comments.

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/datascience_model.py
> +            except Exception as err:
We should probably raise error here and provide the required parameters for `RetentionSetting`

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/datascience_model.py
> +            except Exception as err:
Same here

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/datascience_model.py
> +    @retention_operation_details.setter
Why do we need the property setter, instead of adding the -with method?

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/model_metadata.py
> +        self.customer_notification_type = customer_notification_type if customer_notification_type is not None else CustomerNotificationType.NONE
This can be simplified as:
```
self.customer_notification_type = customer_notification_type or CustomerNotificationType.NONE
```
Same below

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/model_metadata.py
> +        return f"ModelBackupSetting(is_backup_enabled={self.is_backup_enabled}, backup_region={self.backup_region}, customer_notification_type={self.customer_notification_type})"
Can we change this to represent the info as yaml format? Same below

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/model_metadata.py
> +        self.archive_state = archive_state if archive_state is not None else SettingStatus.PENDING
```
self.archive_state = archive_state or SettingStatus.PENDING
```
Same below

2024-10-14 16:40 UTC, lu-ohai commented on ads/model/model_metadata.py
> +                 backup_state: Optional['SettingStatus'] = None,
Why the SettingStatus is string format here?

2024-10-23 00:22 UTC, mrDzurb commented
@iamishaan could you add more details in the PR description?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/service/oci_datascience_model.py
> +            if ex.status == 404:
In case if any other error occurs, the method will not return any result.

```
except ServiceError as ex:
      if ex.status == 404:
            raise ModelArtifactNotFoundError()
      raise
```

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/service/oci_datascience_model.py
> +            self, model_id: str, restore_model_for_hours_specified: Optional[int] = None
NIT: The ```restore_duration_hours``` would be more intuitive name.

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +
NIT: remove extra empty lines

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +            restore_model_for_hours_specified : Optional[int]
NIT: formatting?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        model_id: str,
This either should be a class method or ```model_id``` parameter is not required. See the update nethod.

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        restore_model_for_hours_specified: Optional[int] = None,
SHouldn't we have some default value? FOr example 24 hours?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        self.dsc_model.restore_archived_model_artifact(
It can be something like this: 
```
self.dsc_model.restore_archived_model_artifact(
            model_id=self.id,
            restore_model_for_hours_specified=restore_model_for_hours_specified,
        )

return self.sync()
```

check the update method.

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        self.with_backup_setting(self.backup_setting)
Probably we don't need to add it here. The complex attributes mean that some extra logic is required to initialize these attributes. For example if to check the input schema it has some try/catch mechanism to validate the schema.

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        print("Model Dsc spec")
Should be removed?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        print("Model Details from here")
Should be removed?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/model_metadata.py
> +    _value_map = {
Why do we need this map?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/model_metadata.py
> +    @classmethod
Not sure about all of the methods in this class, why do we need them?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/model_metadata.py
> +    def is_valid(cls, state: str) -> bool:
How this method is used?

2024-10-23 00:58 UTC, mrDzurb commented on ads/model/model_metadata.py
> +class ModelBackupSetting:
I think it would be better to move the new added classes to the ```datascience_model.py```. The ```model_metadata.py``` is used for the different purpose. Also please take a look on the ```DataClassSerializable``` class and see how it used in the code. It includes that many pre-define methods.

2024-10-23 10:17 UTC, iamishaan commented on ads/model/service/oci_datascience_model.py
> +            self, model_id: str, restore_model_for_hours_specified: Optional[int] = None
keeping it consistent with the python sdk

2024-10-23 10:17 UTC, iamishaan commented on ads/model/service/oci_datascience_model.py
> +            if ex.status == 404:
update : taking off the try catch

2024-10-23 11:43 UTC, iamishaan commented on ads/model/model_metadata.py
> +    _value_map = {
it is used to verify if the notification type is valid

2024-10-23 11:47 UTC, iamishaan commented on ads/model/model_metadata.py
> +    _value_map = {
was using it to validate type earlier,  removing it now

2024-10-23 11:53 UTC, iamishaan commented on ads/model/model_metadata.py
> +    def is_valid(cls, state: str) -> bool:
to verify if the notificationType instance is being created with a valid notification type

2024-10-23 18:18 UTC, iamishaan commented on ads/model/datascience_model.py
> +            except Exception as err:
updated the code

2024-10-23 18:20 UTC, iamishaan commented on ads/model/datascience_model.py
> +        print("Model Details from here")
removed

2024-10-23 18:20 UTC, iamishaan commented on ads/model/datascience_model.py
> +            restore_model_for_hours_specified : Optional[int]
done

2024-10-23 18:20 UTC, iamishaan commented on ads/model/datascience_model.py
> +
done

2024-10-23 19:46 UTC, iamishaan commented on ads/model/datascience_model.py
> +    @retention_operation_details.setter
removed

2024-10-23 19:46 UTC, iamishaan commented on ads/model/model_metadata.py
> +        self.customer_notification_type = customer_notification_type if customer_notification_type is not None else CustomerNotificationType.NONE
done

2024-10-23 19:46 UTC, iamishaan commented on ads/model/model_metadata.py
> +        return f"ModelBackupSetting(is_backup_enabled={self.is_backup_enabled}, backup_region={self.backup_region}, customer_notification_type={self.customer_notification_type})"
done

2024-10-23 19:46 UTC, iamishaan commented on ads/model/model_metadata.py
> +        self.archive_state = archive_state if archive_state is not None else SettingStatus.PENDING
done

2024-10-23 22:04 UTC, mrDzurb commented on ads/model/datascience_model.py
> +class ModelBackupSetting:
The ```class ModelBackupSetting:``` can be replaced with 

```
@dataclass(repr=False)
class ModelBackupSetting(DataClassSerializable):
      is_backup_enabled: Optional[bool] = None,
      backup_region: Optional[str] = None,
      customer_notification_type: Optional[str] = None

      def validate(self) -> bool:
                    pass
```

The DataClassSerializable is already implements bunch of the helper functions like form_dict, to_tict, from_json, e.t.c. 

DITO for the other classes.

2024-10-23 22:27 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        model_id: str,
With this update the case shared below will not work. I would rather prefer to remove the ```model_id``` attribute from the function. 

This case will not work:
```
DataScienceModel.from_id("OCID"). restore_model()
```
It will expect from e to provide OCID one more time, 
like this
```
DataScienceModel.from_id("OCID"). restore_model("OCID")
```
But why should i do this, if I already provided the OCID before? 

**The better solution would be**

```
    def restore_model(
            cls,
            restore_model_for_hours_specified: Optional[int] = HOURS_24,
    ):

    if not self.id:
          raise ValueError("Model needs to be saved to the model catalog before it can be updated.")
```

Or if we really want to support both cases below

```
DataScienceModel.from_id("OCID"). restore_model()
DataScienceModel.restore_model("OCID")
```

Then the solution could be 

```
@class_or_instance_method
def restore_model(
            cls,
            model_id: Optional[str] = None,
            restore_model_for_hours_specified: Optional[int] = HOURS_24,
    ):

   if not inspect.isclass(cls): # if the instance used
        pass
   
   # otherwise the class is used
   
   # see GenericModel.update_deployment as example.    
```

2024-10-24 10:27 UTC, iamishaan commented on ads/model/datascience_model.py
> +        model_id: str,
Have updated the method to use self and model_id isn't a required parameter anymore now.
just passing it to `restore_archived_model_artifact` method here

```
self.dsc_model.restore_archived_model_artifact(
            model_id=self.id,
            restore_model_for_hours_specified=restore_model_for_hours_specified,
        )
```

2024-10-24 10:30 UTC, iamishaan commented on ads/model/datascience_model.py
> +        restore_model_for_hours_specified: Optional[int] = None,
That is already handled in backend, if the value passed is null, it defaults it to 24 hours

2024-10-24 10:34 UTC, iamishaan commented on ads/model/datascience_model.py
> +        self.dsc_model.restore_archived_model_artifact(
updated

2024-10-24 10:38 UTC, iamishaan commented on ads/model/datascience_model.py
> +        print("Model Dsc spec")
removed

2024-10-24 10:48 UTC, iamishaan commented on ads/model/service/oci_datascience_model.py
> +            self, model_id: str, restore_model_for_hours_specified: Optional[int] = None
have refactored the method

2024-10-24 10:52 UTC, iamishaan commented on ads/model/model_metadata.py
> +            self,
undo-ed

2024-10-24 11:11 UTC, iamishaan commented on ads/model/datascience_model.py
> +    def is_valid(cls, value):
updated

2024-10-24 11:19 UTC, iamishaan commented on ads/model/datascience_model.py
> +    def value(self):
removed the value method

2024-10-24 15:29 UTC, mrDzurb commented on ads/model/datascience_model.py
> +        self.dsc_model.restore_archived_model_artifact(
The ```return self.sync()``` would get the updated model, in this case user would have the object containing the fresh status and details. Otherwise, after the calling this method user will have an old object.

2024-10-24 15:29 UTC, mrDzurb commented on ads/model/datascience_model.py
> +            self,
Formatting issue?

2024-10-24 18:49 UTC, mrDzurb approved these changes

2024-10-25 04:37 UTC, mrDzurb approved these changes

2024-10-28 16:56 UTC, lu-ohai approved these changes

2024-10-29 05:21 UTC, merged